In [1]:
import numpy as np
import cv2 as cv2

In [2]:
p = np.array([2,4,3])
l = np.array([1,2,2])

In [3]:
np.abs(np.dot(l, np.transpose(p)))/(p[2]*(np.sqrt(l[0]**2+l[1]**2)))

2.3851391759997758

In [4]:
import numpy as np
import cv2

# Camera parameters
focal_length = 1720
principal_point = np.array([680, 610])

# Rotation matrix and translation vector
rotation_vector = np.array([-0.1, 0.1, -0.2])
R = cv2.Rodrigues(rotation_vector)[0]
translation_vector = np.array([[0.09], [0.05], [0.05]])

# Construct the camera matrix
K = np.array([[focal_length, 0, principal_point[0]],
              [0, focal_length, principal_point[1]],
              [0, 0, 1]])

# Combine the intrinsic and extrinsic parameters
projection_matrix = np.dot(K, np.hstack((R, translation_vector)))

print("Projection matrix:")
print(projection_matrix)


Projection matrix:
[[ 1.61665860e+03  2.57925114e+02  8.60633257e+02  1.88800000e+02]
 [-4.03449658e+02  1.61075318e+03  7.57101420e+02  1.16500000e+02]
 [-8.90528958e-02 -1.08953096e-01  9.90049900e-01  5.00000000e-02]]


In [5]:
point_w = np.array([-0.03, 0.01, 0.59, 1]) ##husk at gøre det til homogenous koordinater
x = np.dot(projection_matrix, np.transpose(point_w))

In [6]:
print(x[0]/x[2], x[1]/x[2]) ## tilbage til ikke homogenous

1023.5037710382543 930.2975675125872
